name: DsTeam
version: 1.0.2
main: com.dobeshadow.dsteam.DsTeam
api-version: "1.21"
author: DobeShadow
description: Lightweight temporary team system with PvP protection, summon, and GUI

commands:
  team:
    description: Team commands
    usage: /<command> <create|invite|accept|deny|join|kick|leave|disband|summon|gui|info>
    aliases: [pteam, pt]

permissions:
  dsteam.use:
    description: Allows using all team commands
    default: true
  dsteam.admin:
    description: Admin bypass for team restrictions
    default: op
